changelog:
  categories:
    - title: "New Features"
      labels:
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "Performance"
      labels:
        - perf
    - title: "Refactoring"
      labels:
        - refactor
    - title: "Documentation"
      labels:
        - docs
    - title: "Testing"
      labels:
        - test
    - title: "Other"
      labels:
        - chore
        - "*"
